// Dummy data for the entire platform

export const blogPosts = [
  {
    id: "1",
    slug: "building-custom-dashboards",
    title: "Building Custom Dashboards for Modern Businesses",
    excerpt: "Learn how custom dashboards can transform your business operations and improve decision-making.",
    content: "# Building Custom Dashboards\n\nCustom dashboards are essential for modern businesses...",
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=400&fit=crop",
    tags: ["Dashboards", "Business Intelligence"],
    date: "2024-11-20",
    published: true,
  },
  {
    id: "2",
    slug: "inventory-management-best-practices",
    title: "Inventory Management Best Practices",
    excerpt: "Discover the best practices for implementing an effective inventory management system.",
    content: "# Inventory Management\n\nEffective inventory management is crucial...",
    image: "https://images.unsplash.com/photo-1553413077-190dd305871c?w=800&h=400&fit=crop",
    tags: ["Inventory", "Systems"],
    date: "2024-11-18",
    published: true,
  },
  {
    id: "3",
    slug: "automation-python-scripts",
    title: "Automating Workflows with Python",
    excerpt: "How Python scripts can automate repetitive tasks and increase productivity.",
    content: "# Automation with Python\n\nPython is an excellent tool for automation...",
    image: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800&h=400&fit=crop",
    tags: ["Python", "Automation"],
    date: "2024-11-15",
    published: true,
  },
];

export const portfolioItems = [
  {
    id: "1",
    title: "FinanceTrack Pro",
    type: "SaaS Dashboard",
    description: "Comprehensive financial tracking and analytics platform for SMBs",
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600&h=400&fit=crop",
    tech: ["React", "Node.js", "PostgreSQL", "Chart.js"],
    features: ["Real-time analytics", "Multi-currency support", "Report generation"],
  },
  {
    id: "2",
    title: "InventoryHub",
    type: "Inventory System",
    description: "Complete inventory management solution with barcode scanning",
    image: "https://images.unsplash.com/photo-1553413077-190dd305871c?w=600&h=400&fit=crop",
    tech: ["React", "Express", "MongoDB", "Redis"],
    features: ["Barcode scanning", "Low stock alerts", "Multi-warehouse"],
  },
  {
    id: "3",
    title: "AutoScheduler",
    type: "Automation Tool",
    description: "Python-based task scheduler with email notifications",
    image: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=600&h=400&fit=crop",
    tech: ["Python", "Django", "Celery", "PostgreSQL"],
    features: ["Cron-like scheduling", "Email notifications", "API integrations"],
  },
];

export const demos = [
  {
    id: "1",
    title: "Analytics Dashboard Demo",
    type: "Dashboard",
    link: "#",
    thumbnail: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400&h=300&fit=crop",
  },
  {
    id: "2",
    title: "E-commerce Admin Demo",
    type: "Admin Panel",
    link: "#",
    thumbnail: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=400&h=300&fit=crop",
  },
  {
    id: "3",
    title: "CRM System Demo",
    type: "CRM",
    link: "#",
    thumbnail: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&h=300&fit=crop",
  },
];

export const users = [
  {
    id: "1",
    name: "John Smith",
    email: "john.smith@example.com",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=John",
    role: "Admin",
    status: "Active",
    country: "United States",
    username: "johnsmith",
  },
  {
    id: "2",
    name: "Sarah Johnson",
    email: "sarah.j@example.com",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah",
    role: "Client",
    status: "Active",
    country: "Canada",
    username: "sarahj",
  },
  {
    id: "3",
    name: "Mike Wilson",
    email: "mike.w@example.com",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Mike",
    role: "Client",
    status: "Suspended",
    country: "United Kingdom",
    username: "mikew",
  },
];

export const projects = [
  {
    id: "1",
    title: "E-Commerce Platform",
    client: "Sarah Johnson",
    clientId: "2",
    type: "Website",
    status: "Active",
    updated: "2024-11-22",
    description: "Full-featured e-commerce platform with payment integration",
    tags: ["React", "Stripe", "Node.js"],
    files: [
      { name: "design-mockups.fig", type: "Figma", size: "2.4 MB" },
      { name: "requirements.pdf", type: "PDF", size: "890 KB" },
    ],
  },
  {
    id: "2",
    title: "Inventory Management System",
    client: "Mike Wilson",
    clientId: "3",
    type: "Dashboard",
    status: "In Progress",
    updated: "2024-11-23",
    description: "Custom inventory tracking system with barcode scanning",
    tags: ["React", "PostgreSQL", "Express"],
    files: [
      { name: "database-schema.sql", type: "SQL", size: "145 KB" },
      { name: "api-docs.pdf", type: "PDF", size: "1.2 MB" },
    ],
  },
  {
    id: "3",
    title: "Data Analytics Dashboard",
    client: "John Smith",
    clientId: "1",
    type: "Analytics",
    status: "Completed",
    updated: "2024-11-15",
    description: "Real-time analytics dashboard with custom reporting",
    tags: ["React", "Chart.js", "MongoDB"],
    files: [
      { name: "user-guide.pdf", type: "PDF", size: "3.1 MB" },
      { name: "deployment-notes.md", type: "Markdown", size: "45 KB" },
    ],
  },
];

export const licenses = [
  {
    id: "1",
    key: "XXXX-XXXX-XXXX-ABC123",
    fullKey: "ZD24-E8F2-9A1C-ABC123",
    project: "E-Commerce Platform",
    projectId: "1",
    client: "Sarah Johnson",
    status: "Active",
    expires: "2025-11-22",
    domains: ["example.com", "www.example.com"],
    allowSubdomains: true,
  },
  {
    id: "2",
    key: "XXXX-XXXX-XXXX-DEF456",
    fullKey: "ZD24-B3D9-7E4F-DEF456",
    project: "Inventory Management System",
    projectId: "2",
    client: "Mike Wilson",
    status: "Active",
    expires: "2025-12-01",
    domains: ["inventory.example.com"],
    allowSubdomains: false,
  },
  {
    id: "3",
    key: "XXXX-XXXX-XXXX-GHI789",
    fullKey: "ZD24-C1A5-4F2E-GHI789",
    project: "Data Analytics Dashboard",
    projectId: "3",
    client: "John Smith",
    status: "Expired",
    expires: "2024-10-15",
    domains: ["analytics.example.com"],
    allowSubdomains: true,
  },
];

export const tickets = [
  {
    id: "1",
    subject: "Login Issue on Dashboard",
    status: "Open",
    updated: "2024-11-23",
    client: "Sarah Johnson",
    clientId: "2",
    messages: [
      {
        id: "1",
        sender: "Sarah Johnson",
        text: "I'm having trouble logging into the dashboard. It says invalid credentials.",
        time: "2024-11-23 10:30 AM",
        isSupport: false,
      },
      {
        id: "2",
        sender: "Support Team",
        text: "Hi Sarah, let me check your account. Can you confirm the email you're using?",
        time: "2024-11-23 10:45 AM",
        isSupport: true,
      },
      {
        id: "3",
        sender: "Sarah Johnson",
        text: "Yes, it's sarah.j@example.com",
        time: "2024-11-23 11:00 AM",
        isSupport: false,
      },
    ],
  },
  {
    id: "2",
    subject: "Feature Request: Export Function",
    status: "In Progress",
    updated: "2024-11-22",
    client: "Mike Wilson",
    clientId: "3",
    messages: [
      {
        id: "1",
        sender: "Mike Wilson",
        text: "Can we add an export to CSV feature for the inventory reports?",
        time: "2024-11-22 2:15 PM",
        isSupport: false,
      },
      {
        id: "2",
        sender: "Support Team",
        text: "Great suggestion! I'll forward this to the development team.",
        time: "2024-11-22 3:00 PM",
        isSupport: true,
      },
    ],
  },
];

export const invoices = [
  {
    id: "INV-001",
    date: "2024-11-01",
    amount: "$299.00",
    status: "Paid",
    client: "Sarah Johnson",
  },
  {
    id: "INV-002",
    date: "2024-11-15",
    amount: "$499.00",
    status: "Paid",
    client: "Mike Wilson",
  },
  {
    id: "INV-003",
    date: "2024-11-20",
    amount: "$199.00",
    status: "Pending",
    client: "John Smith",
  },
];

export const activityLogs = [
  {
    id: "1",
    time: "2024-11-23 14:30:25",
    user: "Sarah Johnson",
    userId: "2",
    event: "login",
    description: "User logged in successfully",
    page: "/client",
    ip: "192.168.1.105",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
  },
  {
    id: "2",
    time: "2024-11-23 14:25:10",
    user: "Admin",
    userId: "1",
    event: "update",
    description: "Updated project status",
    page: "/admin/projects",
    ip: "192.168.1.100",
    userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36",
  },
  {
    id: "3",
    time: "2024-11-23 13:45:00",
    user: "Mike Wilson",
    userId: "3",
    event: "security",
    description: "Possible devtools usage detected",
    page: "/client/projects",
    ip: "192.168.1.120",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
  },
  {
    id: "4",
    time: "2024-11-23 12:15:30",
    user: "Unknown",
    userId: null,
    event: "security",
    description: "Suspicious domain access attempt",
    page: "/admin",
    ip: "203.0.113.42",
    userAgent: "curl/7.68.0",
  },
];

export const integrations = [
  {
    id: "1",
    name: "GitHub",
    icon: "Github",
    description: "Streamline code management with GitHub integration.",
    connected: false,
  },
  {
    id: "2",
    name: "Discord",
    icon: "MessageSquare",
    description: "Connect with Discord for seamless team communication.",
    connected: false,
  },
  {
    id: "3",
    name: "Stripe",
    icon: "CreditCard",
    description: "Process payments securely with Stripe.",
    connected: true,
  },
  {
    id: "4",
    name: "Gmail",
    icon: "Mail",
    description: "Access and manage Gmail messages effortlessly.",
    connected: true,
  },
  {
    id: "5",
    name: "Figma",
    icon: "Figma",
    description: "View and collaborate on Figma designs in one place.",
    connected: true,
  },
  {
    id: "6",
    name: "Docker",
    icon: "Container",
    description: "Effortlessly manage Docker containers on your dashboard.",
    connected: false,
  },
];
